Upgrade base image
GenSpectrum/LAPIS-SILO pull request #666
Opened 2024-12-18 13:54 UTC by Taepper

resolves #663

### Summary

The base image was still at ubuntu:22.04. Upgrading this gives us access to a newer compiler version

## PR Checklist

- [ ] All necessary documentation has been adapted or there is an issue to do so.
- [ ] The implemented feature is covered by an appropriate test.

2025-01-06 10:07 UTC, Taepper commented
Installing conan with `pipx` works seamlessly, however it is installed under `~/. local/bin`, which is not in `$PATH` by default. Running the recommended `pipx ensurepath` would add it to `$PATH` but a new shell would need to be started, which we would need to do from the `Dockerfile` itself? For now I specify the full path to the `conan` binary instead.

2025-01-13 12:09 UTC, fengelniederhammer requested changes
LGTM :+1: 

Let's just rework the commit messages: 
* "fix: correctly specify and copy the conanprofile for arm architectures" doesn't need to be a `fix`. This doesn't affect any released artifact.
* The other "fix: install conan with pipx instead of pip" can maybe simply be squashed into the `feat` commit? We don't need this separately in the changelog.

2025-01-15 08:42 UTC, fengelniederhammer commented
I'm wondering why it shows "There is no change in the changelog. This PR will not produce a new releasable version."

Maybe we need to generate the missed release again by hand?

2025-01-15 08:52 UTC, Taepper commented
Ah, I also caught that, but was confused. Your point might be the right approach

2025-01-15 10:18 UTC, merged